name: Unpack
on: [push, workflow_dispatch]
permissions:
  contents: write
jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          shopt -s nullglob
          z=(*.zip)
          if [ ${#z[@]} -gt 0 ]; then
            for f in "${z[@]}"; do unzip -o "$f"; rm "$f"; done
            git config user.name "unpack-bot"
            git config user.email "bot@users.noreply.github.com"
            git add -A
            git commit -m "Update project"
            git push
          fi
